name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Prepare
        run: |
          npm install

      - name: Lint and Test
        run: |
          npm run ng lint
          ###
          # Configure Angular first!
          ####
          # npm test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
          # npm run webdriver-update-ci
          # npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js --webdriver-update=false
          ####

      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run ng build --prod --base-href \"/poc-angular-pwa-ngrx-entity-formly-routerstate/\"
          npm run transloco:optimize
          npx angular-cli-ghpages --repo=https://${{ secrets.GH_TOKEN }}@github.com/SaulMoro/poc-angular-pwa-ngrx-entity-formly-routerstate.git --name="SaulMoro" --email=smoro@atsistemas.com
          # npm run deploy -- --name="SaulMoro" --email=smoro@atsistemas.com
